# -------------------------------------------------------------------
# Paths
paths:
  db:                "database/market_data.db"
  data_dir:          "data"
  logs_dir:          "logs"
  models_dir:        "models"

# -------------------------------------------------------------------
# Symbol groups
symbol_groups:
  top8: ["BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","ADAUSDT","LINKUSDT","AVAXUSDT"]
  meme: ["DOGEUSDT","PEPEUSDT","FLOKIUSDT","WIFUSDT","SHIBUSDT"]
  defi: ["UNIUSDT","AAVEUSDT","SUSHIUSDT","COMPUSDT"]

# -------------------------------------------------------------------
# Timeframes for pipeline & predict
timeframes:
  default: ["1m","5m","15m","30m","1h","4h","1d"]

# -------------------------------------------------------------------
# Preprocessing / feature building
feature_builder:
  target_shift:      5       # how many candles ahead to compute delta, volatility
  tp_threshold:      0.005   # threshold for TP-hit default
  dropna_columns:    ["delta","volatility","target_class","rsi","target_tp_hit","ema_20_slope","ema_50_slope"]

# -------------------------------------------------------------------
# Training defaults
training:
  test_size:         0.15
  random_state:      42
  catboost:
    default_iterations:       700
    default_learning_rate:    0.03
    default_depth:            6
    early_stopping_rounds:    50
    gpu_devices:              "0"

# -------------------------------------------------------------------
# Prediction thresholds (predict.py)
predict:
  min_confidence:            0.08    # minimum (p_max − p_2nd) to consider
  tp_hit_proba_min:          0.60
  sigma_history_max:         0.015
  delta_final_abs_min:       0.002

# -------------------------------------------------------------------
# Logging (overridden in logging.yaml for handlers/formatters)
logging:
  level:           INFO
  format:          "[%(asctime)s] %(levelname)s [%(module)s] %(message)s"

# -------------------------------------------------------------------
# Database
database:
  sqlite_timeout:  60      # seconds per connection
  max_workers:     5       # for parallel updates

# -------------------------------------------------------------------
# Alerts / trade plan
trade_plan:
  confidence_threshold: 0.08
  tp_hit_threshold:     0.55
