# scripts/train.py

import argparse
import sys
import os
import logging

# Ensure the src directory is in the Python path if necessary (usually handled by running from project root)
# sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

# Import config and logging setup first
from src.utils.config import get_config
from src.utils.logging_setup import setup_logging

# Import the main training function
from src.models.train import train_models_for_group_or_symbol

# --- Initial Setup ---
# Load configuration
config = get_config()
SYMBOL_GROUPS = config['symbol_groups'] # Need symbol groups for validation

# Configure logging for this script
setup_logging()
logger = logging.getLogger(__name__) # Use logger specific to this module


# --- Command Line Interface ---

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Обучение моделей CatBoost для заданного таймфрейма и символа/группы.")
    parser.add_argument('--tf', type=str, required=True, help="Таймфрейм для обучения (например: 1m, 5m).")

    # Mutually exclusive group for specifying symbol or group
    symbol_group = parser.add_mutually_exclusive_group(required=True)
    symbol_group.add_argument('--symbol', type=str, help="Обучить модель для отдельного символа (например: BTCUSDT).")
    symbol_group.add_argument('--symbol-group', type=str, help="Обучить модель для предопределенной группы символов из конфига (например: top8, meme).")
    # Note: Training a model on *all* symbols requires preprocess.py to generate features_all_{tf}.pkl
    # and then you would typically call this script with a specific key like '--symbol-group all'
    # or handle 'all' as a special case key in the CLI parsing if it's not a symbol group.
    # Let's allow 'all' as a valid key for --symbol-group for now, distinct from actual groups.


    args = parser.parse_args()

    # Determine the key for the training process (used for filenames and context)
    # This key should match the suffix used when features were generated by preprocess.py
    symbol_or_group_key = None
    if args.symbol_group:
        group_name = args.symbol_group.lower()
        # Allow the special key 'all' or validate against known groups
        if group_name == 'all':
             symbol_or_group_key = 'all'
             logger.info("Обучение модели для всех символов (используется файл features_all_{tf}.pkl).")
        elif group_name in SYMBOL_GROUPS:
            symbol_or_group_key = group_name
            logger.info(f"Обучение модели для группы '{group_name}'.")
        else:
            logger.error(f"Неизвестная группа символов: {args.symbol_group}. Доступные группы: {list(SYMBOL_GROUPS.keys())} или 'all'.")
            sys.exit(1)
    elif args.symbol:
        symbol_or_group_key = args.symbol.upper() # Ensure symbol key is uppercase
        logger.info(f"Обучение модели для символа: {symbol_or_group_key}.")

    if not symbol_or_group_key:
        # This case should be caught by required=True in the argument group, but as a safeguard
        logger.error("Не указан ни --symbol, ни --symbol-group.")
        sys.exit(1)


    # --- Run the training process ---
    try:
        # Call the main training function from the models module
        train_models_for_group_or_symbol(args.tf, symbol_or_group_key)

    except KeyboardInterrupt:
        logger.warning(f"\nОбучение моделей для {symbol_or_group_key} на {args.tf} прервано пользователем (Ctrl+C).")
        sys.exit(130) # Standard Unix exit code for Ctrl+C
    except Exception as e:
        logger.error(f"💥 Непредвиденная ошибка при обучении моделей для {symbol_or_group_key} на {args.tf}: {e}", exc_info=True)
        sys.exit(1) # Standard Unix exit code for general error